### PR TITLE
fix:fix selector by color invalid,bacause matedata is nil

### LINKED ISSUE #35: [bug] metadata没赋值给node，color逻辑不起作用
https://github.com/go-kratos/gateway/blob/8d073a23cdd09d5012b6072cf078a7ce60faecba/client/factory.go#L95

### PR DESCRIPTION
**Pull request by haiyux**
fix #35

### CODE REVIEW

File: client/node.go [hunk 1]
```diff
@@ -51,7 +51,7 @@ func (n *node) Metadata() map[string]string {
 	return n.metadata
 }
 
-func newNode(addr string, protocol config.Protocol, weight *int64, timeout time.Duration) *node {
+func newNode(addr string, protocol config.Protocol, weight *int64, timeout time.Duration, md map[string]string) *node {
```
Comment (ziguss) [inline client/node.go:54]: md还是没赋值给node啊
